/*
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.branselic.services.ConfiguratorLangGrammarAccess;

@SuppressWarnings("all")
public class ConfiguratorLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ConfiguratorLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_SimpleBoolean_LeftParenthesisKeyword_3_0_a;
	protected AbstractElementAlias match_SimpleBoolean_LeftParenthesisKeyword_3_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ConfiguratorLangGrammarAccess) access;
		match_SimpleBoolean_LeftParenthesisKeyword_3_0_a = new TokenAlias(true, true, grammarAccess.getSimpleBooleanAccess().getLeftParenthesisKeyword_3_0());
		match_SimpleBoolean_LeftParenthesisKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getSimpleBooleanAccess().getLeftParenthesisKeyword_3_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_SimpleBoolean_LeftParenthesisKeyword_3_0_a.equals(syntax))
				emit_SimpleBoolean_LeftParenthesisKeyword_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SimpleBoolean_LeftParenthesisKeyword_3_0_p.equals(syntax))
				emit_SimpleBoolean_LeftParenthesisKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'not' booleanexpression+=SimpleBoolean
	 *     (rule start) (ambiguity) operator=Operator
	 *     (rule start) (ambiguity) value=EBoolean
	 *     (rule start) (ambiguity) {And.booleanexpression+=}
	 *     (rule start) (ambiguity) {Or.booleanexpression+=}
	 */
	protected void emit_SimpleBoolean_LeftParenthesisKeyword_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {And.booleanexpression+=}
	 *     (rule start) (ambiguity) {Or.booleanexpression+=}
	 */
	protected void emit_SimpleBoolean_LeftParenthesisKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
