/*
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.branselic.services.ConfiguratorLangGrammarAccess;

@SuppressWarnings("all")
public class ConfiguratorLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ConfiguratorLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_SimpleBoolean_LeftParenthesisKeyword_2_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ConfiguratorLangGrammarAccess) access;
		match_SimpleBoolean_LeftParenthesisKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getSimpleBooleanAccess().getLeftParenthesisKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_SimpleBoolean_LeftParenthesisKeyword_2_0_q.equals(syntax))
				emit_SimpleBoolean_LeftParenthesisKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) operator=[Operator|ID]
	 *     (rule start) (ambiguity) value=EBoolean
	 */
	protected void emit_SimpleBoolean_LeftParenthesisKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
