/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.scoping;

import org.xtext.branselic.scoping.AbstractConfiguratorLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ConfiguratorLangScopeProvider extends AbstractConfiguratorLangScopeProvider {
}
