/*
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.branselic.parser.antlr.internal.InternalConfiguratorLangParser;
import org.xtext.branselic.services.ConfiguratorLangGrammarAccess;

public class ConfiguratorLangParser extends AbstractAntlrParser {

	@Inject
	private ConfiguratorLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConfiguratorLangParser createParser(XtextTokenStream stream) {
		return new InternalConfiguratorLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ConfiguratorModel";
	}

	public ConfiguratorLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConfiguratorLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
