/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getNegation()
 * @model
 * @generated
 */
public interface Negation extends BooleanExpression
{
} // Negation
