/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.validation;

import org.xtext.branselic.validation.AbstractConfiguratorLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConfiguratorLangValidator extends AbstractConfiguratorLangValidator {
}
