/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.branselic.ui.AbstractConfiguratorLangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ConfiguratorLangUiModule extends AbstractConfiguratorLangUiModule {
  public ConfiguratorLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
