/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.branselic.domainmodel.DomainmodelPackage;
import org.xtext.branselic.domainmodel.Int;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntImpl extends TypeImpl implements Int
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.INT;
  }

} //IntImpl
