/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.ui.contentassist;

import org.xtext.branselic.ui.contentassist.AbstractConfiguratorLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ConfiguratorLangProposalProvider extends AbstractConfiguratorLangProposalProvider {
}
