/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getBool()
 * @model
 * @generated
 */
public interface Bool extends Type
{
} // Bool
