/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getBooleanExpression()
 * @model
 * @generated
 */
public interface BooleanExpression extends EObject
{
} // BooleanExpression
