/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.branselic.domainmodel.DomainmodelFactory
 * @model kind="package"
 * @generated
 */
public interface DomainmodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domainmodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://itu.dk/configurator/branselic";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domainmodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainmodelPackage eINSTANCE = org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.ConfiguratorModelImpl <em>Configurator Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.ConfiguratorModelImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getConfiguratorModel()
   * @generated
   */
  int CONFIGURATOR_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Feature</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR_MODEL__FEATURE = 1;

  /**
   * The feature id for the '<em><b>Ruleset</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR_MODEL__RULESET = 2;

  /**
   * The number of structural features of the '<em>Configurator Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.FeatureImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TEXT = 2;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.OperatorImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 2;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__FEATURE = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__OP = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__VALUE = 2;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.TypeImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getType()
   * @generated
   */
  int TYPE = 3;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.BoolImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getBool()
   * @generated
   */
  int BOOL = 4;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.IntImpl <em>Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.IntImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getInt()
   * @generated
   */
  int INT = 5;

  /**
   * The number of structural features of the '<em>Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.EnumImpl <em>Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.EnumImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getEnum()
   * @generated
   */
  int ENUM = 6;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__VALUES = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.RuleSetImpl <em>Rule Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.RuleSetImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getRuleSet()
   * @generated
   */
  int RULE_SET = 7;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_SET__RULE = 0;

  /**
   * The number of structural features of the '<em>Rule Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_SET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.RuleImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getRule()
   * @generated
   */
  int RULE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__IF = 1;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__THEN = 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__TEXT = 3;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.BooleanExpressionImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getBooleanExpression()
   * @generated
   */
  int BOOLEAN_EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Boolean Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.ConstImpl <em>Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.ConstImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getConst()
   * @generated
   */
  int CONST = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__VALUE = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.AtomImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 11;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__OPERATOR = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.NegationImpl <em>Negation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.NegationImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getNegation()
   * @generated
   */
  int NEGATION = 12;

  /**
   * The feature id for the '<em><b>Booleanexpression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION__BOOLEANEXPRESSION = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.AndImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getAnd()
   * @generated
   */
  int AND = 13;

  /**
   * The feature id for the '<em><b>Booleanexpression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__BOOLEANEXPRESSION = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.branselic.domainmodel.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.branselic.domainmodel.impl.OrImpl
   * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getOr()
   * @generated
   */
  int OR = 14;

  /**
   * The feature id for the '<em><b>Booleanexpression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__BOOLEANEXPRESSION = 0;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.ConfiguratorModel <em>Configurator Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configurator Model</em>'.
   * @see org.xtext.branselic.domainmodel.ConfiguratorModel
   * @generated
   */
  EClass getConfiguratorModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.ConfiguratorModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.branselic.domainmodel.ConfiguratorModel#getName()
   * @see #getConfiguratorModel()
   * @generated
   */
  EAttribute getConfiguratorModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.branselic.domainmodel.ConfiguratorModel#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Feature</em>'.
   * @see org.xtext.branselic.domainmodel.ConfiguratorModel#getFeature()
   * @see #getConfiguratorModel()
   * @generated
   */
  EReference getConfiguratorModel_Feature();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.ConfiguratorModel#getRuleset <em>Ruleset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ruleset</em>'.
   * @see org.xtext.branselic.domainmodel.ConfiguratorModel#getRuleset()
   * @see #getConfiguratorModel()
   * @generated
   */
  EReference getConfiguratorModel_Ruleset();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.xtext.branselic.domainmodel.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.branselic.domainmodel.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.branselic.domainmodel.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Feature#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.branselic.domainmodel.Feature#getText()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see org.xtext.branselic.domainmodel.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for the reference '{@link org.xtext.branselic.domainmodel.Operator#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Feature</em>'.
   * @see org.xtext.branselic.domainmodel.Operator#getFeature()
   * @see #getOperator()
   * @generated
   */
  EReference getOperator_Feature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Operator#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.branselic.domainmodel.Operator#getOp()
   * @see #getOperator()
   * @generated
   */
  EAttribute getOperator_Op();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Operator#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.branselic.domainmodel.Operator#getValue()
   * @see #getOperator()
   * @generated
   */
  EAttribute getOperator_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.branselic.domainmodel.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see org.xtext.branselic.domainmodel.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Int <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int</em>'.
   * @see org.xtext.branselic.domainmodel.Int
   * @generated
   */
  EClass getInt();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Enum <em>Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum</em>'.
   * @see org.xtext.branselic.domainmodel.Enum
   * @generated
   */
  EClass getEnum();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.branselic.domainmodel.Enum#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.branselic.domainmodel.Enum#getValues()
   * @see #getEnum()
   * @generated
   */
  EAttribute getEnum_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.RuleSet <em>Rule Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Set</em>'.
   * @see org.xtext.branselic.domainmodel.RuleSet
   * @generated
   */
  EClass getRuleSet();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.branselic.domainmodel.RuleSet#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rule</em>'.
   * @see org.xtext.branselic.domainmodel.RuleSet#getRule()
   * @see #getRuleSet()
   * @generated
   */
  EReference getRuleSet_Rule();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.branselic.domainmodel.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.branselic.domainmodel.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.Rule#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see org.xtext.branselic.domainmodel.Rule#getIf()
   * @see #getRule()
   * @generated
   */
  EReference getRule_If();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.Rule#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see org.xtext.branselic.domainmodel.Rule#getThen()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Then();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Rule#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.branselic.domainmodel.Rule#getText()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression</em>'.
   * @see org.xtext.branselic.domainmodel.BooleanExpression
   * @generated
   */
  EClass getBooleanExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Const <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const</em>'.
   * @see org.xtext.branselic.domainmodel.Const
   * @generated
   */
  EClass getConst();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.branselic.domainmodel.Const#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.branselic.domainmodel.Const#isValue()
   * @see #getConst()
   * @generated
   */
  EAttribute getConst_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see org.xtext.branselic.domainmodel.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.Atom#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see org.xtext.branselic.domainmodel.Atom#getOperator()
   * @see #getAtom()
   * @generated
   */
  EReference getAtom_Operator();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Negation <em>Negation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negation</em>'.
   * @see org.xtext.branselic.domainmodel.Negation
   * @generated
   */
  EClass getNegation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.branselic.domainmodel.Negation#getBooleanexpression <em>Booleanexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Booleanexpression</em>'.
   * @see org.xtext.branselic.domainmodel.Negation#getBooleanexpression()
   * @see #getNegation()
   * @generated
   */
  EReference getNegation_Booleanexpression();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.xtext.branselic.domainmodel.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.branselic.domainmodel.And#getBooleanexpression <em>Booleanexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Booleanexpression</em>'.
   * @see org.xtext.branselic.domainmodel.And#getBooleanexpression()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Booleanexpression();

  /**
   * Returns the meta object for class '{@link org.xtext.branselic.domainmodel.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see org.xtext.branselic.domainmodel.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.branselic.domainmodel.Or#getBooleanexpression <em>Booleanexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Booleanexpression</em>'.
   * @see org.xtext.branselic.domainmodel.Or#getBooleanexpression()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Booleanexpression();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainmodelFactory getDomainmodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.ConfiguratorModelImpl <em>Configurator Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.ConfiguratorModelImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getConfiguratorModel()
     * @generated
     */
    EClass CONFIGURATOR_MODEL = eINSTANCE.getConfiguratorModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATOR_MODEL__NAME = eINSTANCE.getConfiguratorModel_Name();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATOR_MODEL__FEATURE = eINSTANCE.getConfiguratorModel_Feature();

    /**
     * The meta object literal for the '<em><b>Ruleset</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATOR_MODEL__RULESET = eINSTANCE.getConfiguratorModel_Ruleset();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.FeatureImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TYPE = eINSTANCE.getFeature_Type();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__TEXT = eINSTANCE.getFeature_Text();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.OperatorImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATOR__FEATURE = eINSTANCE.getOperator_Feature();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__OP = eINSTANCE.getOperator_Op();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__VALUE = eINSTANCE.getOperator_Value();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.TypeImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.BoolImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.IntImpl <em>Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.IntImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getInt()
     * @generated
     */
    EClass INT = eINSTANCE.getInt();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.EnumImpl <em>Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.EnumImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getEnum()
     * @generated
     */
    EClass ENUM = eINSTANCE.getEnum();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM__VALUES = eINSTANCE.getEnum_Values();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.RuleSetImpl <em>Rule Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.RuleSetImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getRuleSet()
     * @generated
     */
    EClass RULE_SET = eINSTANCE.getRuleSet();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_SET__RULE = eINSTANCE.getRuleSet_Rule();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.RuleImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__IF = eINSTANCE.getRule_If();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__THEN = eINSTANCE.getRule_Then();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__TEXT = eINSTANCE.getRule_Text();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.BooleanExpressionImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getBooleanExpression()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION = eINSTANCE.getBooleanExpression();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.ConstImpl <em>Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.ConstImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getConst()
     * @generated
     */
    EClass CONST = eINSTANCE.getConst();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST__VALUE = eINSTANCE.getConst_Value();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.AtomImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOM__OPERATOR = eINSTANCE.getAtom_Operator();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.NegationImpl <em>Negation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.NegationImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getNegation()
     * @generated
     */
    EClass NEGATION = eINSTANCE.getNegation();

    /**
     * The meta object literal for the '<em><b>Booleanexpression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATION__BOOLEANEXPRESSION = eINSTANCE.getNegation_Booleanexpression();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.AndImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Booleanexpression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__BOOLEANEXPRESSION = eINSTANCE.getAnd_Booleanexpression();

    /**
     * The meta object literal for the '{@link org.xtext.branselic.domainmodel.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.branselic.domainmodel.impl.OrImpl
     * @see org.xtext.branselic.domainmodel.impl.DomainmodelPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Booleanexpression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__BOOLEANEXPRESSION = eINSTANCE.getOr_Booleanexpression();

  }

} //DomainmodelPackage
