/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.branselic.domainmodel.Negation#getBooleanexpression <em>Booleanexpression</em>}</li>
 * </ul>
 *
 * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getNegation()
 * @model
 * @generated
 */
public interface Negation extends BooleanExpression
{
  /**
   * Returns the value of the '<em><b>Booleanexpression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.branselic.domainmodel.BooleanExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Booleanexpression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Booleanexpression</em>' containment reference list.
   * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getNegation_Booleanexpression()
   * @model containment="true"
   * @generated
   */
  EList<BooleanExpression> getBooleanexpression();

} // Negation
