/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.branselic.domainmodel.DomainmodelPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
