/**
 * generated by Xtext 2.10.0
 */
package org.xtext.branselic;

import org.xtext.branselic.AbstractConfiguratorLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConfiguratorLangRuntimeModule extends AbstractConfiguratorLangRuntimeModule {
}
